baseURL = "https://parsecsreach.org"
languageCode = "en-us"
title = "Parsecs Reach"
theme = "hugo-PaperMod"
paginate = 10
Copyright = "All rights reserved - 2022"
Author = "Emily Selwood"
#canonifyurls = true

[params]
  [cover]
    hidden = true
    hiddenInSingle = true
    image = "img/moon.jpg"
  env = "production"
  description = "Emily's personal blog"
  metadescription = "Emily's Personal blog"
  cover = "img/moon.jpg"
  author = "Emily Selwood"
  authorlocation = "Oxfordshire, UK"
  authorwebsite = "https://parsecsreach.org"
  authorbio= "Software Engineer - Sort of full stack but not the normal stack"
  authoravatar="img/profilePic.jpg"
  PostNavLinks = true
  ShowShareButtons=true
  logo = ""
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "emilyselwood"
  twitterName = "emilywselwood"
  mainSections="post"
  
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

[Params.social]
    twitter = "emilywselwood"
    mastodonName = "@emily_s@mastodon.me.uk"

[Params]
  ShowFullTextinRSS=true
  description = "Emily's personal blog"

[[main.params]]
  ShowPostNavLinks=true

[[menu.main]]
  name = "Home"
  weight = -100
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Projects"
  weight = -110
  identifier = "projects"
  url = "/projects"

[[menu.main]]
  name = ""
  weight = -120
  identifier = "github"
  url = "https://github.com/emilyselwood"
  pre = "<svg width=\"18\" height=\"18\" class=\"logo-social\" stroke=\"none\" viewBox=\"0 0 11.493062 11.209467\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M 5.746044,0 C 2.572808,0 0,2.572808 0,5.74675 c 0,2.538941 1.646414,4.69265 3.929944,5.452886 0.287514,0.05256 0.392289,-0.124883 0.392289,-0.277283 0,-0.136173 -0.0049,-0.49777 -0.0078,-0.977195 C 2.715997,10.292291 2.378741,9.174691 2.378741,9.174691 2.117333,8.511116 1.740566,8.334375 1.740566,8.334375 1.218808,7.977716 1.780076,7.984772 1.780076,7.984772 2.356868,8.025692 2.660257,8.577086 2.660257,8.577086 3.172843,9.45515 4.005398,9.201503 4.332776,9.054747 4.384986,8.683272 4.533154,8.429978 4.697548,8.286397 3.421551,8.141405 2.079937,7.648222 2.079937,5.446183 c 0,-0.627239 0.224014,-1.140178 0.591609,-1.541991 -0.05927,-0.145345 -0.25647,-0.729545 0.05609,-1.520825 0,0 0.4826,-0.154517 1.580445,0.589138 C 4.766339,2.845153 5.258111,2.7813 5.746709,2.779183 6.2346,2.781283 6.726372,2.845153 7.185336,2.972505 8.282475,2.22885 8.764017,2.383367 8.764017,2.383367 c 0.313619,0.79128 0.116416,1.37548 0.05715,1.520825 0.3683,0.401813 0.590903,0.914752 0.590903,1.541991 0,2.207683 -1.343731,2.693458 -2.623961,2.835628 0.206375,0.177447 0.390172,0.528108 0.390172,1.06433 0,0.767998 -0.0071,1.387828 -0.0071,1.576212 0,0.153811 0.103364,0.332669 0.395111,0.276577 2.281767,-0.761647 3.92677,-2.913944 3.92677,-5.45218 C 11.493062,2.572808 8.919901,0 5.745959,0\"/></svg>"


[[menu.main]]
  name = ""
  weight = -130
  identifier = "mastodon"
  url = "https://mastodon.me.uk/@emily_s"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 417.8 512\" class=\"logo-social\" width=\"18\" height=\"18\"><path d=\"M417.8 179.1c0-97.2-63.7-125.7-63.7-125.7-62.5-28.7-228.5-28.4-290.4 0 0 0-63.7 28.5-63.7 125.7 0 115.7-6.6 259.4 105.6 289.1 40.5 10.7 75.3 13 103.3 11.4 50.8-2.8 79.3-18.1 79.3-18.1l-1.7-36.9s-36.3 11.4-77.1 10.1c-40.4-1.4-83-4.4-89.6-54-.6-4.4-.9-9-.9-13.9 85.6 20.9 158.6 9.1 178.7 6.7 56.1-6.7 105-41.3 111.2-72.9 9.8-49.8 9-121.5 9-121.5zm-75.1 125.2h-46.6V190.1c0-49.7-64-51.6-64 6.9v62.5h-46.3V197c0-58.5-64-56.6-64-6.9v114.2H75.1c0-122.1-5.2-147.9 18.4-175 25.9-28.9 79.8-30.8 103.8 6.1l11.6 19.5 11.6-19.5c24.1-37.1 78.1-34.8 103.8-6.1 23.7 27.3 18.4 53 18.4 175z\"/></svg>"


# [[menu.main]]
#   name = "Orb Viewer"
#   weight = -140
#   identifier = "orb viwer"
#   url = "https://parsecsreach.org/orbviewer"